server:
    port: 12345

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shop?&serverTimezone=Asia/Seoul&characterEncoding=utf8
        username: root
        password: root
    jackson:
        property-naming-strategy: LOWER_CAMEL_CASE
        show-sql: true
        serialization:
            fail-on-empty-beans: false
    mvc:
        hiddenmethod:
            filter:
                enabled: true

    jpa:
        properties:
            hibernate:
                show_sql: true   # 실행되는 쿼리 콘솔 출력
                format_sql: true # 쿼리 가독성 좋게 포맷팅

                hbm2ddl:
                    auto: update

    servlet:
      multipart:
          max-file-size: 20MB           # 파일 한 개당 최대 사이즈
          max-request-size: 100MB       # 요청당 최대 파일 크

jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400

productImageLocation: C:/shop/product  # 상품 이미지 업로드 경로
uploadPath: file:///C:/shop/           # 리소스 업로드 경로
